FROM debian:buster

ARG WP_PATH
ARG WP_URL

RUN apt update -y && \
    apt upgrade -y && \
    apt install nginx -y && \
    apt install gettext -y && \
    apt install openssl -y && \
    apt install default-mysql-client -y

RUN mkdir -p /etc/nginx/ssl
RUN openssl req -x509 -nodes -out /etc/nginx/ssl/inception.crt -keyout /etc/nginx/ssl/inception.key -subj "/C=FR/ST=IDF/L=Paris/O=42/OU=42/CN=zrebhi.42.fr/UID=zrebhi"

COPY conf/nginx.conf /etc/nginx/nginx.conf

CMD [ "nginx", "-g", "daemon off;" ]